theme: jekyll-theme-minimal
title: [Daniel Kasenberg]
description: [PhD candidate at Human-Robot Interaction Lab at Tufts University]
linkedin_url: "https://www.linkedin.com/in/daniel-kasenberg-120672b"
twitter_handle: dkasenberg
my_name: [Daniel Kasenberg]
